version: '3.8'

services:
  s3-emulator:
    image: minio/minio
    container_name: aether-s3
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      - MINIO_ROOT_USER=local_access_key
      - MINIO_ROOT_PASSWORD=local_secret_key
    command: server /data --console-address ":9001"
    volumes:
      - s3-data:/data

volumes:
  s3-data:
