name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up ./server --path-as-root --project a984c8a9-4a96-442d-b3a4-da1d13de2163 --environment ca7ea859-3dc6-4715-b875-49d0de54b6cc --service aether-backend --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up ./client --path-as-root --project a984c8a9-4a96-442d-b3a4-da1d13de2163 --environment ca7ea859-3dc6-4715-b875-49d0de54b6cc --service aether-frontend --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
